#!/bin/sh

for f in *.typ; do
    if [ -z $(cat $f) ]; then 
        # rm $f # delete empty files
        continue # maybe it is just better to skip the file for compilation
    fi
    typst compile $f pdfs/$f.pdf
done